rapid7/smbj-rpc

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrCloseHandleRequest.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrCloseHandleResponse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrCloseHandleRequest.java
Tested the following snippet
```
SecurityAccountManagerService service = new SecurityAccountManagerService(transport);
service.openDomain("", SID.fromString("S-1-5-32"));
ServerHandle handle = service.getServerHandle("");
DomainHandle handle2 = service.openDomain(handle, SID.fromString("S-1-5-32"));
service.closeHandle(handle2);
service.closeHandle(handle);
connection.close();
```
> Added support for SAMR close handle

- src/main/java/com/rapid7/client/dcerpc/io/PacketInput.java
- src/main/java/com/rapid7/client/dcerpc/io/PacketOutput.java
- src/main/java/com/rapid7/client/dcerpc/objects/RPC_UNICODE_STRING.java
- src/test/java/com/rapid7/client/dcerpc/objects/TEST_RPC_UNICODE_STRING.java
This is a replacement for PacketInput/PacketOutput string marshalling which only allows the string to be a top level deferral.
RPC_UNICODE_STRING allows the structure to be placed anywhere within a request stack.
> Adds RPC_UNICODE_STRING

- pom.xml
- src/test/java/com/rapid7/client/dcerpc/objects/Test_RPC_SID.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_RPC_UNICODE_STRING.java
We were previously using an older version of several maven dependencies which dependended on compile+test of Junit < 4.
However, JUnit >= 4 is required for TestNG to pick up on the tests. Relevant maven plugins have been updated.
- Fixing RPC_SID and RPC_UNICODE_STRING names to match TestNG pattern
- Fixing RPC_UNICODE_STRING tests broken by alignment
- Forcing source/target JDK 1.7
> Updating mvn dependencies so that TestNG will be executed

- src/main/java/com/rapid7/client/dcerpc/msvcctl/objects/ServiceConfigInfo.java
Some parameters of ServiceConfigInfo are mandatory, and may not be set to null. Changing the class to reflect this.
> Changing service config info mandatory params to final

- src/main/java/com/rapid7/client/dcerpc/mslsad/LocalSecurityAuthorityService.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarQueryInformationPolicyRequest.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPR_POLICY_PRIMARY_DOM_INFO.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/POLICY_INFORMATION_CLASS.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_LSAPR_POLICY_PRIMARY_DOM_INFO.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_POLICY_INFORMATION_CLASS.java
- Adding LSAPR_POLICY_PRIMARY_DOM_INFO struct
- Adding POLICY_PRIMARY_DOMAIN_INFORMATION to POLICY_INFORMATION_CLASS enum
- Mapping POLICY_PRIMARY_DOMAIN_INFORMATION to LSAPR_POLICY_PRIMARY_DOM_INFO via LsarQueryInformationPolicyRequest.PolicyPrimaryDomainInformation
- Adding getPolicyPrimaryDomainInformation to LocalSecurityAuthorityService
> Adds LSAPR_POLICY_PRIMARY_DOM_INFO to LsarQueryInformationPolicy

- src/main/java/com/rapid7/client/dcerpc/mslsad/LocalSecurityAuthorityService.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarQueryInformationPolicyRequest.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPR_POLICY_ACCOUNT_DOM_INFO.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/POLICY_INFORMATION_CLASS.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/messages/Test_LsarQueryInformationPolicyResponse.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_LSAPR_POLICY_ACCOUNT_DOM_INFO.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_POLICY_INFORMATION_CLASS.java
* Adding LSAPR_POLICY_ACCOUNT_DOM_INFO struct
* Adding POLICY_ACCOUNT_DOMAIN_INFORMATION to POLICY_INFORMATION_CLASS enum
* Mapping POLICY_ACCOUNT_DOMAIN_INFORMATION to LSAPR_POLICY_ACCOUNT_DOM_INFO via LsarQueryInformationPolicyRequest.PolicyAccountDomainInformation
* Adding getPolicyAccountDomainInformation to LocalSecurityAuthorityService
* Adding unit tests for LsarQueryInformationPolicyResponse
> Adds LSAPR_POLICY_ACCOUNT_DOM_INFO to LsarQueryInformationPolicy

- pom.xml
Windows uses cp1252 by default, which will not be compatible with any source files containing utf-8 characters and expecting those bytes to be identical.
> Forcing UTF-8 source encoding

- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRPolicyAccountDomInfo.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRPolicyPrimaryDomInfo.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/SAMPRRIDEnumeration.java
- src/main/java/com/rapid7/client/dcerpc/objects/RPCUnicodeString.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_LSAPRPolicyAccountDomInfo.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_LSAPRPolicyPrimaryDomInfo.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_EnumeratedDomains.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_RPCUnicodeString.java
- RPCUnicodeString subclasses are now public
- Relevant structs now explicitly require either a null terminated or non null terminated RPCUnicodeString
- RPCUnicodeString static convenience methods are now within the respective subclasses
> Refactoring RPCUnicodeString

- src/main/java/com/rapid7/client/dcerpc/io/PacketInput.java
- src/main/java/com/rapid7/client/dcerpc/io/PacketOutput.java
- src/main/java/com/rapid7/client/dcerpc/io/PrimitiveInput.java
- src/main/java/com/rapid7/client/dcerpc/io/PrimitiveOutput.java
- src/main/java/com/rapid7/client/dcerpc/objects/RPCSID.java
- src/main/java/com/rapid7/client/dcerpc/objects/RPCUnicodeString.java
- src/test/java/com/rapid7/client/dcerpc/io/Test_PrimitiveInput.java
- src/test/java/com/rapid7/client/dcerpc/io/Test_PrimitiveOutput.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_RPCSID.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_RPCUnicodeString.java
- Uses appropriate return type for: `PacketInput.readUnsignedByte()`
- Adds convenience method: `PacketInput.readUnsignedInt()`
- Adds convenience method: `PacketOutput.writeInt(long)`
- Adds full unit test coverage including signed/unsigned parameters for `PacketInput`/`PacketOutput`
- Improves `RPCUnicodeString` and `RPCSID`:
* Each of these structs now read/write unsigned primitives where required
* Now skipping bytes instead of parsing numbers where the values are not used
> Adds additional unsigned primitive support and test coverage

- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarQueryInformationPolicyRequest.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarQueryInformationPolicyResponse.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/messages/Test_LsarQueryInformationPolicyRequest.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/messages/Test_LsarQueryInformationPolicyResponse.java
Uses same inner class format as SamrQueryInformationUser and SamrQueryInformationGroup
> Refactoring LsarQueryInformationPolicy

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQueryInformationGroupRequest.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQueryInformationGroupResponse.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/GroupInformationClass.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/SAMPRGroupGeneralInformation.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrQueryInformationGroupRequest.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrQueryInformationGroupResponse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_GroupInformationClass.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRGroupGeneralInformation.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_UserInformationClass.java
- Adds SamrQueryInformationGroupRequest/Response with initial support for level 1 (SAMPR_GROUP_GENERAL_INFORMATION)
- Adds SAMPR_GROUP_GENERAL_INFORMATION
- Adds SecurityAccountManagerService.getGroupGeneralInformation
- Full unit test coverage where applicable
> Adds SamrQueryInformationGroup with level 1 support (SAMPR_GROUP_GENERAL_INFORMATION)

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQueryInformationAliasRequest.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQueryInformationAliasResponse.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQuerySecurityObjectRequest.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQuerySecurityObjectResponse.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/AliasInformationClass.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/SAMPRAliasGeneralInformation.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/SAMPRSRSecurityDescriptor.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/Test_SecurityAccountManagerService.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrQueryInformationAliasRequest.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrQueryInformationAliasResponse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrQuerySecurityObjectRequest.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrQuerySecurityObjectResponse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_AliasInformationClass.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRAliasGeneralInformation.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRSRSecurityDescriptor.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRUserAllInformation.java
- Adds `SamrQuerySecurityObjectRequest`/`Response`
- Adds `SecurityAccountManagerService.getSecurityObject`
- Changed `SAMPRSRSecurityDescriptor` to use `byte[]` instead of `char[]`. The contents of this response is treated as a payload for a SECURITY_DESCRIPTOR and not an array of integers.
- Full unit test coverage
> Adds SamrQuerySecurityObject

- src/main/java/com/rapid7/client/dcerpc/PDUFault.java
- src/main/java/com/rapid7/client/dcerpc/transport/RPCTransport.java
- src/main/java/com/rapid7/client/dcerpc/transport/exceptions/RPCFaultException.java
- src/test/java/com/rapid7/client/dcerpc/Test_RPCFault.java
- src/test/java/com/rapid7/client/dcerpc/transport/exceptions/Test_RPCFaultException.java
Previously, we would attempt to unmarshall the response regardless of the PDU. However, we should only attempt this when the PDU is RESPONSE, otherwise the payload is not what will be expected.
- RPCFault has been added which capture all well known FAULT and REJECT codes
- RPCFaultException has been added which holds the context of the FAULT or REJECT response
- In the event that the PDU returned from our request is not RESPONSE but is FAULT or REJECT, we will best-effort parse the fault/reject code, and throw RPCFaultException
- In the event that the PDU returned from our request is not RESPONSE but is not FAULT and not REJECT, we will throw a generic IOException
> Handling PDUType.FAULT and PDUType.REJECT by throwing RPCFaultException

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQueryInformationDomain2Request.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQueryInformationDomainRequest.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrQueryInformationDomainResponse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrQueryInformationDomain.java
- Duplicating logic in SamrQueryInformationDomain into SamrQueryInformationDomain2. They are separate requests and it's cleaner to handle them separately
- Using the same approach to information request/response as done in SamrQueryInformationGroup and other similar structures
> Refactoring SamrQueryInformationDomain and SamrQueryInformationDomain2

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrLookupNamesInDomainRequest.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrLookupNamesInDomainResponse.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/SAMPRULongArray.java
- src/main/java/com/rapid7/client/dcerpc/objects/SIDNameUse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrLookupNamesInDomainRequest.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrLookupNamesInDomainResponse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRULongArray.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_SIDNameUse.java
* Adds `com.rapid7.client.dcerpc.mssamr.messages.SamrLookupNamesInDomainRequest`/`Response` (SamrLookupNamesInDomain)
* Adds `com.rapid7.client.dcerpc.mssamr.objects.SAMPRULongArray` (SAMPR_ULONG_ARRAY). Represents array of unsigned longs
* Adds `com.rapid7.client.dcerpc.mssamr.SecurityAccountManagerService.getNamesInDomain` convenience method. Accepts varargs of strings instead of RPCUnicodeString
* Adds `com.rapid7.client.dcerpc.objects.SIDNameUse`. SID_NAME_USE entries in `SamrLookupNamesInDomainResponse.getUse()` are not mapped to the enum itself. This allows the client to inspect the raw values should any issues arise. Use of
> Supporting SamrLookupNamesInDomain

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrLookupDomainInSamServerRequest.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrLookupDomainInSamServerResponse.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrLookupDomainInSamServerRequest.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/messages/Test_SamrLookupDomainInSamServerResponse.java
* Adds `com.rapid7.client.dcerpc.mssamr.messages.SamrLookupDomainInSamServerRequest`/`Response` (SamrLookupDomainInSamServer)
* Adds `com.rapid7.client.dcerpc.mssamr.SecurityAccountManagerService.getSIDForDomain` convenience method. Accepts a string instead of RPCUnicodeString
* Full test coverage
>  Adds support for SamrLookupDomainInSamServer

- src/main/java/com/rapid7/client/dcerpc/mslsad/LocalSecurityAuthorityService.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/dto/LSAPLookupLevel.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarLookupNamesRequest.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarLookupNamesResponse.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarLookupSIDsRequest.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/messages/LsarLookupSIDsResponse.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRReferencedDomainList.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRTranslatedName.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRTranslatedNames.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRTranslatedSID.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRTranslatedSIDs.java
- src/main/java/com/rapid7/client/dcerpc/mslsad/objects/LSAPRTrustInformation.java
- src/main/java/com/rapid7/client/dcerpc/service/Service.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/Test_LookupNames.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/Test_LookupSIDs.java
- Conformant arrays were being marshalled/unmarshalled incorrectly. Using proper preamble-entity-deferral strategy now
- Some alignments were missing, which cause issues for multiple entries
- Methods have been renamed to reflect the RPC layer documentation
- Documentation has been added where it was missing
>  Corrects marshalling errors in LsarLookupNames and LsarLookupSIDs 

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/objects/RPCUnicodeString.java
- src/main/java/com/rapid7/client/dcerpc/objects/WChar.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_LSAPRPolicyAccountDomInfo.java
- src/test/java/com/rapid7/client/dcerpc/mslsad/objects/Test_LSAPRPolicyPrimaryDomInfo.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRAliasGeneralInformation.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRGroupGeneralInformation.java
- src/test/java/com/rapid7/client/dcerpc/mssamr/objects/Test_SAMPRUserAllInformation.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_RPCUnicodeString.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_WChar.java
- This struct is analogous to w_char_t, and should be used instead of PacketInput/PacketOutput string variants
- RPCUnicodeString (which is a string buffer) now uses WChar as its w_char_t*
- Added unit tests where applicable
- Added documentation where missing
> Adds WChar struct

- src/main/java/com/rapid7/client/dcerpc/msrrp/RegistryService.java
- src/main/java/com/rapid7/client/dcerpc/msrrp/messages/BaseRegGetKeySecurityRequest.java
- src/main/java/com/rapid7/client/dcerpc/msrrp/messages/BaseRegGetKeySecurityResponse.java
- src/main/java/com/rapid7/client/dcerpc/msrrp/messages/BaseRegOpenKey.java
- src/main/java/com/rapid7/client/dcerpc/msrrp/objects/RPCSecurityDescriptor.java
- src/test/java/com/rapid7/client/dcerpc/msrrp/messages/Test_BaseRegOpenKey.java
Added an argument to openKey to allow setting desired access. For some reason maximum allowed does not provide system security access.
Added a method in RegistryService to getKeySecurity.
Tested by getting SACL and DACL for HKLM/System/CurrentControlSet on a windows target.
> Added getKeySecurity method to RegistryService

- src/main/java/com/rapid7/client/dcerpc/objects/WChar.java
- src/test/java/com/rapid7/client/dcerpc/objects/Test_RPCUnicodeString.java
A target can return a null terminated RPCUnicodeString that has a length (ActualLength) of 0.
This corrects an issue with negative string lengths when this situation is encountered.
> Fixes issue with 0 length null terminated strings

- src/main/java/com/rapid7/client/dcerpc/mssamr/SecurityAccountManagerService.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/messages/SamrGetMembersInGroupResponse.java
- src/main/java/com/rapid7/client/dcerpc/mssamr/objects/SAMPRGetMembersBuffer.java
- src/main/java/com/rapid7/client/dcerpc/objects/RPCConformantArray.java
Fixes the following:
```
java.lang.NullPointerException
at com.rapid7.client.dcerpc.io.PacketInput.readUnmarshallable(PacketInput.java:31)
at com.rapid7.client.dcerpc.mssamr.objects.SAMPRGetMembersBuffer.unmarshalDeferrals(SAMPRGetMembersBuffer.java:82)
at com.rapid7.client.dcerpc.io.PacketInput.readUnmarshallable(PacketInput.java:33)
at com.rapid7.client.dcerpc.mssamr.messages.SamrGetMembersInGroupResponse.unmarshalResponse(SamrGetMembersInGroupResponse.java:39)
at com.rapid7.client.dcerpc.messages.RequestResponse.unmarshal(RequestResponse.java:84)
at com.rapid7.client.dcerpc.transport.RPCTransport.call(RPCTransport.java:116)
at com.rapid7.client.dcerpc.service.Service.call(Service.java:46)
at com.rapid7.client.dcerpc.service.Service.callExpect(Service.java:55)
at …
```
> Fixes NPE encountered when no members are found within a group

- .github/CONTRIBUTING
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE
Add github templates for:
- contributing info (displayed in pull request workflow)
- new pull requests
- new issues
To see what the new issue workflow looks like, see recog-java:
https://github.com/rapid7/recog-java/issues/new/choose
> Add github templates

- pom.xml
- src/main/java/com/rapid7/client/dcerpc/dto/ContextHandle.java
- src/main/java/com/rapid7/client/dcerpc/dto/SID.java
- src/main/java/com/rapid7/client/dcerpc/io/HexifyImpl.java
- src/main/java/com/rapid7/client/dcerpc/msrrp/dto/RegistryValue.java
Upgrade SMBJ to support SMBv3.
Explanation of why these changes are being proposed, including any links to other relevant issues or pull requests.
Integration tests succeed.
> Update smbj and bouncy castle to support SMBv3

- pom.xml
Overriding the bouncycastle dependency bcprov-jdk18on in SMBJ as that version has vulnerabilities. 
Bumped the version of commons-io to a version without vulnerabilities.
Explanation of why these changes are being proposed, including any links to other relevant issues or pull requests.
Ran existing unit and integration tests
- Bug fix (non-breaking change which fixes an issue)
> Overriding the vulnerable version of bouncy castle in smbj
